### ISSUE TITLE
Ability to Apply Crop Augmentation on selected classes

### ISSUE THREAD

**Issue by m-ali-awan** [jacobmarks/fiftyone-albumentations-plugin#1]
Hi there, 
Thanks for this amazing plugin.

Recently, I came across the problem of under-represented classes in an instance segmentation dataset. And it posed such problem, eg if I am labeling house objects, and `stairs-bannisters` , `wall-painting` are classes. Now, if I simply increase images, bannisters also increase exponentially, 
But on the otherhand, if I can augment the dataset with flixibilty of Cropping only around the `wall-painting` class, I can reduce this data-imbalance by some extent..

So, can we do this currently, 

Thanks

**Comment by jacobmarks** [comment]
Hey @m-ali-awan , thanks for the note. I see that you posted a similar issue in the Albumentations repo. The answer is that you can *absolutely* do this with FiftyOne + Albumentations using this plugin.

- Step 0: Install the latest versions of FiftyOne and Albumentations `pip install -U fiftyone albumentations`
- Step 1: Install the FiftyOne Albumentations plugin: `fiftyone plugins download https://github.com/jacobmarks/fiftyone-albumentations-plugin`
- Step 2: Load your dataset into FiftyOne. Depending on the data, you may want to use [Classification](https://docs.voxel51.com/user_guide/using_datasets.html#classification) or [Detection](https://docs.voxel51.com/user_guide/using_datasets.html#object-detection) labels for your objects.
- Step 3: Filter your dataset for just the `wall-painting` objects. You can do this in the FiftyOne App by checking the appropriate box in the sidebar for that label, and then hitting the bookmark icon above the sample grid. You should see some "view stages" appear in the view bar
- Step 4: Run the `augment_with_albumentations` operator from the plugin to apply transformations, choosing a Crop transform, the number of augmentations you want per sample, etc, and applying these to **only the current view**, not the entire dataset.
- Step 5: Save the augmentations to the dataset with the `save_albumentations_augmentations` operator.

Hope this helps!

**Comment by m-ali-awan** [comment]
Thanks @jacobmarks for helping me out..

But this will not crop focusing on the desired object, i.e `wall-painting`, as for such functionality we require a CropTransform that does controlled-random crop, and accepts desired class/es and can crop around them...
