### ISSUE TITLE
Fiftyone exits after completing augmentations

### ISSUE THREAD

**Issue by junior-senior** [jacobmarks/fiftyone-albumentations-plugin#2]
I have been applying an augmentation to a dataset, and when the augmentation run completes the screen reloads to include the augmented images in the UI, the console says 'Process finished with exit code 0' and the browser page redirects and says that no session is running. 

I am launching fiftyone with:
session = fo.launch_app(dataset, port=5151)
session.wait()

Version numbers: 
Fifityone = 0.23.8
Plugin installed as per the readme instructions.

**Comment by jacobmarks** [comment]
Hey @junior-senior , I know you mentioned `fiftyone==0.23.8`, so [this issue](https://github.com/voxel51/fiftyone/pull/4198) with the `set_view` operator should be fixed. But you can you try installing FiftyOne from source:

```bash
pip install git+https://github.com/voxel51/fiftyone/
```

If that doesn't fix it, would you mind sharing more details?

- What transformations are you trying to apply?
- What view are you applying the transforms to? Full dataset, selected samples, or current view?
- What version of Albumentations are you using?
- What label types do you have?

**Comment by junior-senior** [comment]
Hey @jacobmarks. I did this (actually I cloned the repo and then installed via bash as per the instructions in readme) and I am still getting the error. I also tried to re-install the plugin and Albumentations with no success.

1. I have tried RandomRotate90, Horizontal Flip and CLAHE individually. It happens on all of them.
2. Happens when applying transform to Full Dataset (2,421) and just one sample. Using 1 transform per sample and 1 tranform.
3. Albumentations version is 1.4.4
4. Segmentation and Detection labels

**Comment by junior-senior** [comment]
I just tried to run the process as a delegated execution and it works fine. 

Edit: It sometimes works fine, other times it doesn't load the augmentations and so I have to refresh the page which causes the program to exit

**Comment by junior-senior** [comment]
Setting:
session = fo.launch_app(dataset, port=5151)
session.wait(-1)

seems to resolve the issue as I can reload the page without the application exiting

**Comment by jacobmarks** [comment]
@junior-senior If you are running FiftyOne from a python process in the terminal, launching the app directly from the command line with `fiftyone app launch`, or from a jupyter notebook, you do not need to use `session.wait()`. 

What is the reasoning behind running this in a Python script? The intent behind the plugin was a more interactive experience, but if there is a use-case for running from scripts, I'd love to know and figure out how to support. If this is the case, I can add a note to the readme about setting `session.wait()` with a negative number as documented [here](https://docs.voxel51.com/api/fiftyone.core.session.html#fiftyone.core.session.Session.wait)

**Comment by junior-senior** [comment]
Only reason really is because that's what the example in the github readme said to do!

**Comment by jacobmarks** [comment]
I see. In the README I didn't explicitly mention a python script, but I also didn't explicitly mention running from notebook or CLI. If someone else runs into this issue I'll update the README. For now I'm going to close this.

Thanks for the feedback/help improving this! :)
