### ISSUE TITLE
Can't enter more than one value for parameters that can take tuples

### ISSUE THREAD

**Issue by junior-senior** [jacobmarks/fiftyone-albumentations-plugin#3]
For MultiplicativeNoise it says: 
If single float image will be multiplied to this number. If tuple of float multiplier will be in range [multiplier[0], multiplier[1]). Default (0.9, 1.1) but in the Multiplier Parameter I can only enter a number and therefore cannot provide a tuple for a custom range. This is the same for other parameters that use more than one value such as GaussNoise and CLAHE.

**Comment by jacobmarks** [comment]
Hey @junior-senior , you are right this was the case. I'm working on the generalization right now. Should be able to do this very shortly.

**Comment by jacobmarks** [comment]
Following up on this. As of the latest commit, most instances of tuples should work across all of the available transforms. To [upgrade](https://github.com/voxel51/fiftyone-plugins/tree/main/plugins/plugins), you can use the `install_plugin` operator from the `@voxel51/plugins` plugin. Closing this issue for now :)

**Comment by junior-senior** [comment]
Thanks for your speedy work!
