### ISSUE TITLE
How can I specify the border mode for Padifneeded?

### ISSUE THREAD

**Issue by darrenjkt** [jacobmarks/fiftyone-albumentations-plugin#6]
Hi Jacob,

Thanks for your work on these plugins and your fix for Padifneeded. I was hoping to use the padding mode of cv2.BORDER_CONSTANT, but it seems like even if I set the pad value = 0, it will still apply the default border mode cv2.BORDER_REFLECT_101. Is there a way to explicitly set the border_mode from the UI fields?

Would also be great if we could set the `position` parameter in the albumentations [function](https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.PadIfNeeded).

**Comment by jacobmarks** [comment]
Hey @darrenjkt , great question! I've just added support for both of these.

- For `position`, enter the string in lowercase, for instance "center", "top_left", etc.
- For `border_mode`, you can now select from the dropdown

Maring this issue as resolved for now :)
