### ISSUE TITLE
Performing an augmentation yields an error on cleanup

### ISSUE THREAD

**Issue by dokutoshi** [jacobmarks/fiftyone-albumentations-plugin#7]
Steps to ### Recreate @jacobmarks 
1. Launch Augmentation operator in FiftyOne web app
2. Select an augmentation e.g. emboss, equalize,
3. Execute the augmentation on a sample set

### Version info
In [6]: print(fo.__version__)
0.23.8

(tf_2.15) leopimentel@XRXC65LQ69s-MBP ~ % fiftyone plugins list
plugin                                   version    enabled    directory
---------------------------------------  ---------  ---------  -------------------------------------------------------------------------------
@voxel51/plugins                         1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/plugins
@voxel51/delegated                       1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/delegated
@voxel51/io                              1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/io
@voxel51/annotation                      1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/annotation
@voxel51/utils                           1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/utils
@voxel51/hello-world                     1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/hello-world
@voxel51/zoo                             1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/zoo
@voxel51/examples                        1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/examples
@voxel51/evaluation                      1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/evaluation
@voxel51/brain                           1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/brain
@voxel51/python-view                     1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/python-view
@voxel51/runs                            1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/runs
@voxel51/indexes                         1.0.0      ✓          /Users/leopimentel/fiftyone/__plugins__/@voxel51/indexes
@jacobmarks/albumentations_augmentation  1.0.7      ✓          /Users/leopimentel/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation

### Error:

▼Error occurred during operator execution

Traceback (most recent call last):
  File "/Users/leopimentel/mambaforge/envs/apple_tensorflow/envs/tf_2.15/lib/python3.11/site-packages/fiftyone/operators/executor.py", line 277, in execute_or_delegate_operator
    result = await do_execute_operator(operator, ctx, exhaust=exhaust)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leopimentel/mambaforge/envs/apple_tensorflow/envs/tf_2.15/lib/python3.11/site-packages/fiftyone/operators/executor.py", line 319, in do_execute_operator
    result = await (
             ^^^^^^^
  File "/Users/leopimentel/mambaforge/envs/apple_tensorflow/envs/tf_2.15/lib/python3.11/site-packages/fiftyone/core/utils.py", line 2317, in run_sync_task
    return await loop.run_in_executor(_get_sync_task_executor(), func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leopimentel/mambaforge/envs/apple_tensorflow/envs/tf_2.15/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leopimentel/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 1044, in execute
    _cleanup_last_transform(ctx.dataset)
  File "/Users/leopimentel/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 788, in _cleanup_last_transform
    os.remove(fp)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/dad5fc1ad2.jpg'

**Comment by jacobmarks** [comment]
Thanks for sharing @dokutoshi ! I just added a check if the file exists before trying to delete. Can you update your version of the plugin and retry?

**Comment by jacobmarks** [comment]
Fixed by https://github.com/jacobmarks/fiftyone-albumentations-plugin/commit/d877c63aa260b56b2b59fc81eeb5bd0691787478
